"""initial

Revision ID: 474640aeb5ad
Revises: 
Create Date: 2026-03-18 16:42:49.165719
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '474640aeb5ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
