"""update_exam_session_fields

Revision ID: 938e94b35826
Revises: ae3f5b2c8d1e
Create Date: 2026-04-21 12:10:00.128460
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '938e94b35826'
down_revision = 'ae3f5b2c8d1e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_sessions', sa.Column('attempt_id', sa.UUID(), nullable=True))
    op.add_column('exam_sessions', sa.Column('device_fingerprint', sa.String(), nullable=True))
    op.add_column('exam_sessions', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('exam_sessions', sa.Column('last_heartbeat', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_foreign_key(None, 'exam_sessions', 'exam_attempts', ['attempt_id'], ['id'])
    op.execute("ALTER TYPE attempt_status ADD VALUE IF NOT EXISTS 'abandoned'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exam_sessions', type_='foreignkey')
    op.drop_column('exam_sessions', 'last_heartbeat')
    op.drop_column('exam_sessions', 'is_active')
    op.drop_column('exam_sessions', 'device_fingerprint')
    op.drop_column('exam_sessions', 'attempt_id')
    # ### end Alembic commands ###
